using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MyLolNexus.RestApi {
    class StaticData {

        public static readonly Dictionary<int, string> summonerSpellById = new Dictionary<int, string>() {
            { 1, "cleanse" },
            { 12, "teleport" },
            { 14, "ignite" },
            { 6, "ghost" },
            { 7, "heal" },
            { 11, "smite" },
            { 3, "exhaust" },
            { 21, "barrier" },
            { 4, "flash" }
        };

        public static readonly Dictionary<int, string> championById = new Dictionary<int, string>() {
            { 21, "MissFortune" },
            { 1, "Annie" },
            { 101, "Xerath" },
            { 2, "Olaf" },
            { 51, "Caitlyn" },
            { 15, "Sivir" },
            { 150, "Gnar" },
            { 104, "Graves" },
            { 92, "Riven" },
            { 16, "Soraka" },
            { 22, "Ashe" },
            { 127, "Lissandra" },
            { 34, "Anivia" },
            { 113, "Sejuani" },
            { 254, "Vi" },
            { 29, "Twitch" },
            { 45, "Veigar" },
            { 20, "Nunu" },
            { 82, "Mordekaiser" },
            { 27, "Singed" },
            { 24, "Jax" },
            { 90, "Malzahar" },
            { 89, "Leona" },
            { 163, "Taliyah" },
            { 222, "Jinx" },
            { 64, "LeeSin" },
            { 134, "Syndra" },
            { 112, "Viktor" },
            { 203, "Kindred" },
            { 114, "Fiora" },
            { 268, "Azir" },
            { 157, "Yasuo" },
            { 117, "Lulu" },
            { 3, "Galio" },
            { 9, "FiddleSticks" },
            { 48, "Trundle" },
            { 38, "Kassadin" },
            { 69, "Cassiopeia" },
            { 14, "Sion" },
            { 28, "Evelynn" },
            { 76, "Nidalee" },
            { 77, "Udyr" },
            { 238, "Zed" },
            { 4, "TwistedFate" },
            { 17, "Teemo" },
            { 83, "Yorick" },
            { 80, "Pantheon" },
            { 36, "DrMundo" },
            { 122, "Darius" },
            { 12, "Alistar" },
            { 133, "Quinn" },
            { 79, "Gragas" },
            { 6, "Urgot" },
            { 39, "Irelia" },
            { 57, "Maokai" },
            { 35, "Shaco" },
            { 19, "Warwick" },
            { 86, "Garen" },
            { 105, "Fizz" },
            { 120, "Hecarim" },
            { 78, "Poppy" },
            { 53, "Blitzcrank" },
            { 25, "Morgana" },
            { 85, "Kennen" },
            { 110, "Varus" },
            { 44, "Taric" },
            { 84, "Akali" },
            { 115, "Ziggs" },
            { 18, "Tristana" },
            { 26, "Zilean" },
            { 119, "Draven" },
            { 11, "MasterYi" },
            { 161, "Velkoz" },
            { 68, "Rumble" },
            { 412, "Thresh" },
            { 5, "XinZhao" },
            { 99, "Lux" },
            { 432, "Bard" },
            { 420, "Illaoi" },
            { 202, "Jhin" },
            { 63, "Brand" },
            { 131, "Diana" },
            { 58, "Renekton" },
            { 96, "KogMaw" },
            { 75, "Nasus" },
            { 103, "Ahri" },
            { 40, "Janna" },
            { 23, "Tryndamere" },
            { 72, "Skarner" },
            { 107, "Rengar" },
            { 154, "Zac" },
            { 67, "Vayne" },
            { 31, "Chogath" },
            { 136, "AurelionSol" },
            { 33, "Rammus" },
            { 126, "Jayce" },
            { 60, "Elise" },
            { 32, "Amumu" },
            { 143, "Zyra" },
            { 43, "Karma" },
            { 106, "Volibear" },
            { 8, "Vladimir" },
            { 201, "Braum" },
            { 55, "Katarina" },
            { 429, "Kalista" },
            { 421, "RekSai" },
            { 13, "Ryze" },
            { 54, "Malphite" },
            { 98, "Shen" },
            { 81, "Ezreal" },
            { 61, "Orianna" },
            { 267, "Nami" },
            { 7, "Leblanc" },
            { 50, "Swain" },
            { 42, "Corki" },
            { 111, "Nautilus" },
            { 41, "Gangplank" },
            { 102, "Shyvana" },
            { 10, "Kayle" },
            { 121, "Khazix" },
            { 59, "JarvanIV" },
            { 56, "Nocturne" },
            { 245, "Ekko" },
            { 62, "MonkeyKing" },
            { 91, "Talon" },
            { 30, "Karthus" },
            { 37, "Sona" },
            { 74, "Heimerdinger" },
            { 223, "TahmKench" },
            { 236, "Lucian" },
            { 266, "Aatrox" }
        };



        public class Team {
            public const long Team1 = 100;
            public const long Team2 = 200;
        }
    }
}
